name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main
      - develop
      - "*"     # chạy mọi branch cho dễ test

jobs:
  test-runner:
    runs-on: self-hosted   # dùng runner Kkanger
    steps:
      - name: Print hostname
        run: |
          echo "Runner is working!"
          echo "Running on: $(hostname)"
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -al

